### ISSUE TITLE
Adding postgresql as a database

### ISSUE THREAD

**Issue by saadb** [kevin-wynn/reactjs-express-generator#6]
I want to use Postgresql as a database, what do you recommend?

**Comment by kevin-wynn** [comment]
There is [node-postgres](https://node-postgres.com/) for connecting to postgres. I can get it added in as a flag for db support by the end of the week

**Comment by saadb** [comment]
That would great 

Could you take a look at the other issue with routing on the server side 
I basically want to add a menu with routing via express, but I can not get to the page 

app . use ( '/users' , users ); 
app . use ( '/upload' , upload ); 

//**************************************************************/ 
//Routes 
// app.use('*', function(req, res) { 
// res.sendFile(path.resolve(__dirname, 'src', 'index.html')); 
// }); 

app . use ( '/' , function ( req , res ) { 
res . sendFile ( path . resolve ( __dirname , 'src/views' , 'index.html' )); 

}); 

app . use ( '/users' , function ( req , res ) { 
res . sendFile ( path . resolve ( __dirname , 'src/views' , 'index.html' )); 

}); 


app . use ( '/upload' , function ( req , res ) { 
res . sendFile ( path . resolve ( __dirname , 'src/views' , 'upload.html' )); 
//res.send('Hello from Upload'); 
}); 

I can not get to upload.html 

Thank you in advance 

Saad

**Comment by kevin-wynn** [comment]
@saadb I'll update that ticket with the details from here, I'm going to be looking into that this weekend. I think there is an overall better solution that I want to achieve here with the generator that will take a little longer to implement but handle things like this much better and cleaner.

I'll push the postgres support tonight and add their docs to the wiki

I'll also open another ticket for overall DB enhancements. I want to add in some terminal prompts to ask for database credentials, this way if you have your db already set up you can supply credentials and the generator will be smart enough to add some sample scripts for you to work with depending on which DB support you're going with

**Comment by kevin-wynn** [comment]
published changes for postgres support, you can use --postgres or -p flags with the generator to install decencies there - will work off new ticket for better db support in the future
